name: motomeetfront
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  http: ^0.13.6
  intl: ^0.17.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  dot_navigation_bar: ^1.0.2
  flutter_map: ^4.0.0
  huawei_map: ^6.11.2+301
  map: ^2.0.2
  vector_map_tiles: ^4.0.0
  geolocator: ^11.0.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3
  
flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    
