name: motomeetfront
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  http: ^1.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  dot_navigation_bar: ^1.0.2
  flutter_map: ^6.0.1
  json_annotation: ^4.9.0
  map: ^2.0.2
  geolocator: ^11.0.0
  flutter_riverpod: ^2.5.1
  flutter_map_animations: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.6.2
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3
  
flutter:
  uses-material-design: true 
  assets:
    - assets/images/

