org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1Ijoiam9zaGRldXRzY2giLCJhIjoiY204Ymw3eDU3MDdjbTJtczZ5d3F5Y3JyZCJ9.KHppmITdie-2hI-OafKrEg
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
